language: r
r:
 - release
 - devel
cache: packages
cran: https://cran.rstudio.com/

before_install:
 - tlmgr install psfrag
 - echo "options(repos = c(CRAN='https://cran.rstudio.com'))" >> ~/.Rprofile
 - sudo apt-get --yes --force-yes update -qq
 - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libprotobuf-dev protobuf-compiler libv8-3.14-dev libjq-dev
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 
r_build_args: --compact-vignettes="gs+qpdf"

r_check_args: --as-cran

addons:
  apt:
    packages: 
      - ghostscript
      - tcl8.5-dev
      - tk8.5-dev